[NERD](https://coderantine.com/Nerds) ADVENTURER, THE entrance WAS THERE WHERE YOU FIRST SAW IT ;)

Adventurer, remmember "SAY FRIEND AND COME IN". This will help you later facing dangerous archives...
